### ISSUE TITLE
/config is missing default path

### ISSUE THREAD

**Issue by OmgImAlexis** [linuxserver/docker-openvpnas#2]
`/config` should default to `/mnt/user/appdata/openvpn-as` instead of just being blank for UNRAID.

**Comment by sparklyballs** [comment]
i hate prefilled paths with a vengenance.

plus with unraid it would be set in the template anyways.

**Comment by OmgImAlexis** [comment]
@sparklyballs where should I open an issue then since it really should have it pre filled for config. Other fields don't matter that much but config should be set by default.

**Comment by sparklyballs** [comment]
i don't think it should, not everyone has the same share for appdata.
