### ISSUE TITLE
Not an Issue - Just need help

### ISSUE THREAD

**Issue by bjay1404** [linuxserver/docker-openvpnas#22]
Hi, I'm trying to get this working with Docker Compose in YAML. Can't seem to get the right yaml config. Can you help?

**Comment by bjay1404** [comment]
`openvpn-as:
  #cap_add:
  #  - NET_ADMIN
  container_name: openvpn
  net: host
  environment:
    - PUID=0
    - PGID=0
    - INTERFACE=ens32
    - TZ=EST
  #ports:
  #  - "1194:1194/udp"
  #  - "9443:9443/tcp"
  #  - "943:943/udp"
  image: linuxserver/openvpn-as
  privileged: true
  #restart: unless-stopped
  volumes:
    - "/opt/docker/openvpnas:/config"
`

**Comment by bjay1404** [comment]
``
openvpn-as:
  #cap_add:
  #  - NET_ADMIN
  container_name: openvpn
  net: host
  environment:
    - PUID=0
    - PGID=0
    - INTERFACE=ens32
    - TZ=EST
  #ports:
  #  - "1194:1194/udp"
  #  - "9443:9443/tcp"
  #  - "943:943/udp"
  image: linuxserver/openvpn-as
  privileged: true
  #restart: unless-stopped
  volumes:
    - "/opt/docker/openvpnas:/config"
``

**Comment by bjay1404** [comment]
openvpn-as:
  container_name: openvpn
  net: host
  environment:
    - PUID=1000
    - PGID=1000
    - INTERFACE=ens32
    - TZ=EST
  image: linuxserver/openvpn-as
  privileged: true
  volumes:
    - "/opt/docker/openvpnas:/config"
    #ports:
    #  - "1194:1194/udp"
    #  - "9443:9443/tcp"
    #  - "943:943/udp"
    #cap_add:
    #  - NET_ADMIN
    #restart: unless-stopped

**Comment by j0nnymoe** [comment]
is this still an issue?
