### ISSUE TITLE
Do start as HTTP, not HTTPS

### ISSUE THREAD

**Issue by Spritekin** [linuxserver/docker-openvpnas#23]
Hi,

First of all, nice image. Well defined.

But I got a problem. I would like to start this image in AWS ECS. This places the container in a machine in a cluster and starts a AWS ElasticLoadBalancer to do health checks and to manage the HTTPS connections.

So I start the container ok and I can go to https://host:943/admin but my browser complains about the certificates. If I do a curl I get:
```
> curl https://172.31.36.254:943/admin
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: https://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

So AWS service health checks are similar to curl except I can't add a -k or --insecure. So they fail.

All the certificates are managed on the LoadBalancer level so I don't have certificates to give to OpenVPN. 

So, is there a way to start it in http mode only? That way I can setup the ELB with the certificates and pass secure requests to the VPN and the health checks won't fail.

Thanks!

**Comment by thelamer** [comment]
I just looked over the access server config file reference and their documentation. There is no config option to run this as a non ssl protocol. I understand using ACM with AWS is convenient , but if you do not want SSL warnings for your users you will need to get a legit certificate and place it in your config folder mount the files are under the: 

```
/config/etc/web-ssl
```

Folder

**Comment by srburton** [comment]
@Spritekin 

What configuration did you use to obtain access to the administrator?

I see trying more without success, I already put port 943 in the security group but still without success, I can't access the panel ...
