### ISSUE TITLE
default admin account with password 'password' does not work

### ISSUE THREAD

**Issue by tsmilam** [linuxserver/docker-openvpnas#24]
The initial credentials of admin:password to log into https://<ip>:943/admin does not work. The error is 'Incorrect login'.

[linuxserverurl]: https://linuxserver.io
[![linuxserver.io](https://raw.githubusercontent.com/linuxserver/docker-templates/master/linuxserver.io/img/linuxserver_medium.png)][linuxserverurl]

**Comment by tsmilam** [comment]
@sparklyballs thanks for checking into this so quickly! This is how I started the container:

`docker create --name=openvpn-as -v /volume1/docker/openvpn/:/config -e PGID=100 -e PUID=1026 -e TZ=America/Indiana/Indianapolis -e INTERFACE=ovs_bond0 --net=host --privileged linuxserver/openvpn-as`

I then set up an nginx reverse proxy for https://vpn.mydomain.com to 192.168.1.10:943

Then I attempt to log in at https://vpn.mydomain.com/admin/ with the username 'admin' and password 'password'. 

![screen shot 2017-09-07 at 10 17 35 am](https://user-images.githubusercontent.com/18430689/30167888-cd8e5c7e-93b5-11e7-8661-ba3723018370.png)

If it's relevant, I'm doing this on a Synology NAS with docker version 1.11.2. I'm sure I'm doing something wrong, just not sure what that might be.

**Comment by sparklyballs** [comment]
all i can tell you is that the container works as outlined in the README and the username and password are correct

any messing about with reverse proxies etc are a separate issue, probably not a good idea and certainly something we can't diagnose for you
