### ISSUE TITLE
Persistent PAM Configuration

### ISSUE THREAD

**Issue by capo42** [linuxserver/docker-openvpnas#30]
Hello all

First off, the Container runns like a charm. It works with Windows, Android and Linux perfect.
BUT!
For my Chromebook i need PAM Configuration according to this Article:
https://www.errietta.me/blog/openvpn-chromebook/

Now the PAM Configuration are not Persistent and will be discarded after an image update.
Do you see any possibilities that you can make the PAM Configuration also Persistent?

Thanks for you Time!
Michele

**Comment by aptalca** [comment]
Did you try this? https://www.chromium.org/chromium-os/how-tos-and-troubleshooting/openvpn-manual-setup

**Comment by homerr** [comment]
Stale, closed.
