### ISSUE TITLE
Can't get udp port listening

### ISSUE THREAD

**Issue by ajhong2** [linuxserver/docker-openvpnas#31]
I'm running this docker on Unraid. As stated in the title, I cannot access from port 1194. (I can't access from 9443 either). According to a netstat the only port out of the three that are listening is 943.

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="openvpn-as" --net="host" --privileged="true" -e TZ="America/Los_Angeles" -e HOST_OS="unRAID" -e "TCP_PORT_943"="943" -e "TCP_PORT_9443"="9443" -e "UDP_PORT_1194"="1194" -e "INTERFACE"="bond0" -e "PGID"="100" -e "PUID"="99" -v "/mnt/user":"/unraid":rw -v "/mnt/user/system/docker/openvpn-as":"/config":rw linuxserver/openvpn-as

a2bae889b851283704259b4de6738e11c5b3f0dfc57d981e867e7f3421a86a53

![connectivity test](https://user-images.githubusercontent.com/31233783/35260566-26c3904e-ffc1-11e7-95c5-e5744f7e7828.PNG)
![status overview](https://user-images.githubusercontent.com/31233783/35260567-26d8f812-ffc1-11e7-9344-5deb31462b6a.PNG)

**Comment by j0nnymoe** [comment]
I don't believe then connectivity test has ever worked. Best thing to test is setup a client and see if it connects.

**Comment by ajhong2** [comment]
I can't connect to port 1194 inside or outside of the network. Since it's not listening I'm thinking it won't ever connect.

According to this video it seems like this user has it working. https://www.youtube.com/watch?v=EfBvvilnasU

Around 7:15 he disables all other ports except udp/1194

**Comment by tobbenb** [comment]
Is bond 0 your correct interface?

**Comment by ajhong2** [comment]
bond0 is the correct interface.

**Comment by j0nnymoe** [comment]
are you setting up this container via cli or the unraid webui? because I believe `-e "TCP_PORT_943"="943" -e "TCP_PORT_9443"="9443" -e "UDP_PORT_1194"="1194"` shouldn't be needed.

**Comment by ajhong2** [comment]
It is being setup in the GUI. That is the output once setup.

**Comment by j0nnymoe** [comment]
Any errors in the docker logs?

**Comment by ajhong2** [comment]
I don't see any.

`[s6-init] making user provided files available at /var/run/s6/etc...exited 0.
[s6-init] ensuring user provided files have correct perms...exited 0.
[fix-attrs.d] applying ownership & permissions fixes...
[fix-attrs.d] done.
[cont-init.d] executing container initialization scripts...
[cont-init.d] 10-adduser: executing...

-------------------------------------
_ ()
| | ___ _ __
| | / __| | | / \
| | \__ \ | | | () |
|_| |___/ |_| \__/


Brought to you by linuxserver.io
We gratefully accept donations at:
https://www.linuxserver.io/donations/
-------------------------------------
GID/UID
-------------------------------------

User uid: 99
User gid: 100
-------------------------------------

[cont-init.d] 10-adduser: exited 0.
[cont-init.d] 20-time: executing...

Current default time zone: 'America/Los_Angeles'
Local time is now: Mon Jan 22 22:06:01 PST 2018.
Universal Time is now: Tue Jan 23 06:06:01 UTC 2018.

[cont-init.d] 20-time: exited 0.
[cont-init.d] 30-config: executing...
[cont-init.d] 30-config: exited 0.
[cont-init.d] 40-openvpn-init: executing...
[cont-init.d] 40-openvpn-init: exited 0.
[cont-init.d] 50-interface: executing...
MOD Default {} {}
MOD Default {} {}
MOD Default {} {}
MOD Default {} {}
[cont-init.d] 50-interface: exited 0.
[cont-init.d] done.
[services.d] starting services
[services.d] done.`

**Comment by tobbenb** [comment]
Can you try to mount the /config to /mnt/cache/appdata/openvpn-as or whatever setup you have for appdata? If you don't have a cache drive, then use /mnt/diskX/

**Comment by j0nnymoe** [comment]
Also, remove `-v "/mnt/user":"/unraid":rw` you don't need to mount your whole array to openvpn-as.

**Comment by ajhong2** [comment]
I have moved the config to /mnt/cache/appdata/openvpn-as and removed the mount for my array. Still no luck.

root@localhost:# /usr/local/emhttp/plugins/dynamix.docker.manager/scripts/docker run -d --name="openvpn-as" --net="host" --privileged="true" -e TZ="America/Los_Angeles" -e HOST_OS="unRAID" -e "TCP_PORT_943"="943" -e "TCP_PORT_9443"="9443" -e "UDP_PORT_1194"="1194" -e "INTERFACE"="bond0" -e "PGID"="100" -e "PUID"="99" -v "/mnt/cache/appdata/openvpn-as":"/config":rw linuxserver/openvpn-as

f52aae700ad7901e06ad5069e72589d19220f5e6072d2c9206e0438e4407a825

Some netstat commands I ran.

root@Tower:/mnt/cache/appdata/openvpn-as/etc# netstat -an | grep 1194
root@Tower:/mnt/cache/appdata/openvpn-as/etc# netstat -an | grep 943
tcp        0      0 10.10.1.254:943         0.0.0.0:*               LISTEN
root@Tower:/mnt/cache/appdata/openvpn-as/etc#

**Comment by j0nnymoe** [comment]
could you do `ifconfig` and post the output please?
Thanks

**Comment by tobbenb** [comment]
Did you start with an empty appdata folder after changing to /mnt/cache?
And please provide the log also.

**Comment by ajhong2** [comment]
[ifconfig.txt](https://github.com/linuxserver/docker-openvpnas/files/1655122/ifconfig.txt)
[openvpn.log](https://github.com/linuxserver/docker-openvpnas/files/1655131/openvpn.log)

My folder /mnt/user/system/docker and /mnt/cache/appdata are actually the same (I guess what you would call a hard link?). I'm not sure why or when I set that up, but it works just fine with all my other apps. I have left it as /mnt/cache/appdata for now though incase it was causing any issues.

**Comment by tobbenb** [comment]
Can you please use an empty folder for the appdata?

**Comment by tobbenb** [comment]
I meant the docker log.

**Comment by ajhong2** [comment]
Unraid makes this file look really ugly for some reason... Please let me know if there's another file you'd like to look at.

[Docker.log](https://github.com/linuxserver/docker-openvpnas/files/1655185/Docker.log)

**Comment by tobbenb** [comment]
Just push the log button to the right of the openvpn-as container and it should look better. But from what I see in the log, it looks good.

**Comment by ajhong2** [comment]
Yeah I didn't see anything that stood out.

[docker.log](https://github.com/linuxserver/docker-openvpnas/files/1655252/docker.log)

**Comment by tobbenb** [comment]
Have you tried to create a user and connect using the openvpn connect?
It works like it should here.

**Comment by ajhong2** [comment]
I have created a user, but I can never get to the login page. I'm trying to access it through UDP port 1194 and not through 943. Port forwarding has been enabled and I have verified that the port is open. However seeing as I can't reach it when on my local network, I know that I can't reach it from outside. (I did try)

**Comment by ajhong2** [comment]
I was following along with the youtube video I had posted earlier and he mentioned security and using this port. I'm not sure why it's not working or listening on this port though when it's configured in the docker settings to do so.

**Comment by tobbenb** [comment]
So you are trying to log in to the webui on udp port 1194? That is not how it works.
You have to log in to the webui on port 943 and download the openvpn profile, then use that with the openvpn connect client. Test it locally first to exclude your router and domain stuff.

**Comment by ajhong2** [comment]
If you look at my first post. In the screenshots I have configured the incoming connection to attempt to connect on port 1194. I'm not looking to access the webgui, I am trying to establish a connection. I have tried the openVPN connect client and it won't connect to that port locally.

**Comment by tobbenb** [comment]
What happens if you connect to the webui, log in with your user, leave it at connect, let's openvpn connect download and install? It should then automatically connect. Well, if you are on windows.

**Comment by ajhong2** [comment]
On Windows it does. I can't seem to figure out why my VM doesn't, but I'm not too concerned about that. I just don't have any access from outside of my local network.

**Comment by j0nnymoe** [comment]
So you are able to connect via your windows client locally? Have you opened your ports on your router?

**Comment by ajhong2** [comment]
Since moving to a fresh appdata I left it defaulted to leave open both TCP 947 and UDP 1194 and this is why I was able to connect. Once I change it to only UDP 1194, it stops working.

I can connect locally, but only through port 947. I currently only have port 1194 open on my router, so I can't connect from outside the network.

**Comment by aptalca** [comment]
Maybe your client is set to connect through tcp only, or maybe your isp is blocking udp on 1194

**Comment by ajhong2** [comment]
The port is open, I just can't get the docker to listen on that port.

**Comment by aptalca** [comment]
Netstat doesn't list that udp port as listening for me either but I can connect on udp just fine. Check your router config and make sure you forwarded the port correctly (correct ip and did udp, not tcp)

You can also check to make sure something else is not using the same port on the host (no way to know since you're running it in host mode, maybe would be an error in openvpn logs). Try changing it to some other random port in the webgui and also change the forwarding on the router

**Comment by tobbenb** [comment]
Did you download a new config after changing to only udp 1194?

**Comment by ajhong2** [comment]
I finally managed to get this working. I attempted a lot of things, but I think this one finally did the trick.

https://lime-technology.com/forums/topic/41631-support-linuxserverio-openvpn-as/?page=29&tab=comments#comment-598988

**Comment by tobbenb** [comment]
If you updated the container, yes. But you installed freshly and you never stated initially that it was updated.
