### ISSUE TITLE
tcp port 9443 not used in container

### ISSUE THREAD

**Issue by ferrymanders** [linuxserver/docker-openvpnas#35]
tcp port 9443 is exposed in the Dockerfile but isn't used by openvpn-as.

When checking the container i couldn't find any processes listening on 9443 and the port is also not listed in the openvpn-as docs : https://openvpn.net/images/pdf/OpenVPN_Access_Server_Sysadmin_Guide_Rev.pdf

I believe this port is exposed in error and best resolve would be to remove it from the expose command so not to confuse any other users.

**Comment by leviwheatcroft** [comment]
It's in the downloaded client.ovpn configs, my client tries to connect on 1194 & 9443. I guess it's defined by this container's config, you can change it in the admin ui anyway.

Regardless, I think it should stay in the readme.

**Comment by aptalca** [comment]
It is the default tcp port for this image
