### ISSUE TITLE
Ubuntu 14.04 pam error with host mode

### ISSUE THREAD

**Issue by jamesjjk** [linuxserver/docker-openvpnas#4]
Hi I'm running the docker-openvpnas server in host mode on Ubuntu 14.04 with the 3.13 kernel (same issue for 3.15) it has a PAM auth issue which renders it impossible to use passwd on 14.04. There is a work around:

https://github.com/phusion/baseimage-docker/issues/181

This is more of an FYI, I will fork and bake in the solution.

**Comment by lonix** [comment]
I Was expecting this solution to come upstream ? to our baseimage at least.

**Comment by seertenedos** [comment]
I am currently hitting this issue with the latest image. is there a work around or fix for it or a particular version that is not affected? I have used the latest version which i think is 13.
