### ISSUE TITLE
Unable to access WebUI

### ISSUE THREAD

**Issue by Sviests** [linuxserver/docker-openvpnas#43]
I just installed the openvpn-as docker image following the instructions, but I am unable to access the WebUI, i checked the config file and it specifies port 943, but the docker ps function does not show that there are any ports used for the container. Am I doing something wrong?

**Comment by Brookke** [comment]
I believe this is because it is in host networking stack so the ports are not listed as there is no need to bind them. To access the GUI you have to access it via https not http, this could be your issue.

**Comment by homerr** [comment]
Pending further comment, closed. Make sure you're using https and yes it'll not show any ports as mapped as it's running in host mode.
